export const MOVIES = [
  {
    id: 1,
    title: "Dune: Part Three",
    year: 2026,
    genre: "Sci-Fi",
    imdb: 8.9,
    rt: 95,
    poster: "🏜️",
    duration: "2h 45m",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya"],
    synopsis: "Kontynuacja epickiej sagi na Arrakis. Paul Atryda staje przed ostatecznym wyborem, który zadecyduje o losach całego wszechświata.",
    platforms: [
      { name: "Netflix", price: "33 zł/msc", color: "#E50914" },
      { name: "Max", price: "29.99 zł/msc", color: "#002BE7" },
    ],
  },
  {
    id: 2,
    title: "The Brutalist",
    year: 2025,
    genre: "Dramat",
    imdb: 8.4,
    rt: 97,
    poster: "🏛️",
    duration: "3h 35m",
    director: "Brady Corbet",
    cast: ["Adrien Brody", "Felicity Jones"],
    synopsis: "Historia węgierskiego architekta uciekającego z powojennej Europy do Ameryki w poszukiwaniu wolności i sensu.",
    platforms: [
      { name: "Apple TV+", price: "34.99 zł/msc", color: "#555555" },
    ],
  },
  {
    id: 3,
    title: "Konklawe",
    year: 2024,
    genre: "Thriller",
    imdb: 7.8,
    rt: 93,
    poster: "⛪",
    duration: "2h 00m",
    director: "Edward Berger",
    cast: ["Ralph Fiennes", "Stanley Tucci"],
    synopsis: "Po śmierci papieża kardynałowie zbierają się w Watykanie, by wybrać następcę. Intrygi i tajemnice wychodzą na jaw.",
    platforms: [
      { name: "Canal+", price: "45 zł/msc", color: "#1A1A1A" },
      { name: "Amazon Prime", price: "49 zł/rok", color: "#00A8E1" },
    ],
  },
  {
    id: 4,
    title: "Oppenheimer",
    year: 2023,
    genre: "Biograficzny",
    imdb: 8.3,
    rt: 93,
    poster: "☢️",
    duration: "3h 01m",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt"],
    synopsis: "Epicka historia twórcy bomby atomowej — triumf nauki i moralne konsekwencje, które zmieniły bieg historii.",
    platforms: [
      { name: "SkyShowtime", price: "19.99 zł/msc", color: "#6B3FA0" },
    ],
  },
  {
    id: 5,
    title: "Shogun",
    year: 2024,
    genre: "Serial",
    imdb: 8.7,
    rt: 99,
    poster: "⚔️",
    duration: "10 odc.",
    director: "Rachel Kondo",
    cast: ["Hiroyuki Sanada", "Anna Sawai"],
    synopsis: "Angielski żeglarz trafia do feudalnej Japonii i wplątuje się w grę o władzę między potężnymi klanami.",
    platforms: [
      { name: "Disney+", price: "37.99 zł/msc", color: "#0063E5" },
    ],
  },
  {
    id: 6,
    title: "Diabelskie miasto",
    year: 2025,
    genre: "Serial",
    imdb: 8.1,
    rt: 88,
    poster: "🌆",
    duration: "8 odc.",
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio"],
    synopsis: "Mroczny kryminał osadzony w Chicago lat 20. — prohibicja, gangsterzy i jeden detektyw, który widział za dużo.",
    platforms: [
      { name: "Apple TV+", price: "34.99 zł/msc", color: "#555555" },
      { name: "Netflix", price: "33 zł/msc", color: "#E50914" },
    ],
  },
];

export const SPORTS = [
  {
    id: 1,
    event: "Liga Mistrzów — Półfinał",
    teams: "Real Madryt vs Arsenal",
    date: "8 kwi 2026, 21:00",
    icon: "⚽",
    platforms: [
      { name: "Canal+", price: "45 zł/msc" },
      { name: "TVP Sport", price: "Za darmo" },
    ],
  },
  {
    id: 2,
    event: "Roland Garros — Finał",
    teams: "Świątek vs Sabalenka",
    date: "12 cze 2026, 15:00",
    icon: "🎾",
    platforms: [
      { name: "Eurosport", price: "29.99 zł/msc" },
      { name: "TVP Sport", price: "Za darmo" },
    ],
  },
  {
    id: 3,
    event: "GP Monako — Wyścig główny",
    teams: "Formula 1",
    date: "24 maj 2026, 15:00",
    icon: "🏎️",
    platforms: [
      { name: "Viaplay", price: "34 zł/msc" },
    ],
  },
  {
    id: 4,
    event: "Ekstraklasa — 30. kolejka",
    teams: "Lech Poznań vs Legia Warszawa",
    date: "12 kwi 2026, 17:30",
    icon: "🏆",
    platforms: [
      { name: "Canal+", price: "45 zł/msc" },
    ],
  },
];

export const RANKINGS = [
  { rank: 1, title: "Shawshank Redemption", score: 9.3, year: 1994 },
  { rank: 2, title: "The Godfather", score: 9.2, year: 1972 },
  { rank: 3, title: "The Dark Knight", score: 9.0, year: 2008 },
  { rank: 4, title: "Schindler's List", score: 8.9, year: 1993 },
  { rank: 5, title: "Dune: Part Three", score: 8.9, year: 2026 },
  { rank: 6, title: "12 Angry Men", score: 8.9, year: 1957 },
  { rank: 7, title: "Lord of the Rings", score: 8.9, year: 2003 },
  { rank: 8, title: "Pulp Fiction", score: 8.8, year: 1994 },
];
