export const t = {
  bg: "var(--t-bg)",
  s:  "var(--t-s)",
  sh: "var(--t-sh)",
  a:  "var(--t-a)",
  ad: "var(--t-ad)",
  ab: "var(--t-ab)",
  tx: "var(--t-tx)",
  tm: "var(--t-tm)",
  b:  "var(--t-b)",
  w:  "var(--t-w)",
  wa: "var(--t-wa)",
  d:  "var(--t-d)",
  da: "var(--t-da)",
};
